version: '3.7'

services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    ports:
      - 443:443
    volumes: 
      - wordpress:/var/www/html/wordpress
    networks:
      - inception
    depends_on: 
      - wordpress
    restart: always

  mariadb:
    build:
      context: ./requirements/mariadb
      args:
        DB_USER: ${DB_USER}
        DB_DATABASE: ${DB_DATABASE}
        DB_USER_PASSWORD: ${DB_USER_PASSWORD}
        DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      dockerfile: Dockerfile
    container_name: mariadb
    image: mariadb
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always
    expose:
      - 3306

  wordpress:
    build:
      context: ./requirements/wordpress
      args:
        HOST: ${HOST}
        TITLE: ${TITLE}
        WP_DOMAIN: ${WP_DOMAIN}
        WP_ADMIN: ${WP_ADMIN}
        WP_ADMIN_PW: ${WP_ADMIN_PW}
        WP_ADMIN_MAIL: ${WP_ADMIN_MAIL}
      dockerfile: Dockerfile
      args:
        DB_DATABASE: ${DB_DATABASE}
        DB_USER: ${DB_USER}
        DB_USER_PASSWORD: ${DB_USER_PASSWORD}
        HOST: ${HOST}
        WP_DOMAIN: ${WP_DONAIN}
        TITLE: ${TITLE}
        WP_ADMIN: ${WP_ADMIN}
        DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        WP_ADMIN_MAIL: ${WP_ADMIN_MAIL}
        USER_BIS: ${USER_BIS}
        USER_BIS_MAIL: ${USER_BIS_MAIL}
    container_name: wordpress
    image: wordpress
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    restart: always
    expose:
      - 9000

networks:
  inception:
    driver: bridge
    name: inception

volumes:
  wordpress:
    driver: local
    name: wordpress
    driver_opts:
      type: 'none'
      device: '/home/nibernar/data/wordpress'
      o: 'bind'

  mariadb:
    driver: local
    name: mariadb
    driver_opts:
      type: 'none'
      device: '/home/nibernar/data/mariadb'
      o: 'bind'
